import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service — Composable',
  description: "Composable's Terms of Service — the agreement governing your use of the Composable platform.",
}

export default function TermsPage() {
  return (
    <div className="py-20 bg-white">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="mb-12">
          <p className="text-xs font-semibold tracking-widest text-brand-600 uppercase mb-4">Legal</p>
          <h1 className="font-display text-4xl font-extrabold text-ink-950 mb-4">Terms of Service</h1>
          <p className="text-ink-500 text-sm">Last updated: April 27, 2026</p>
        </div>

        <div className="prose prose-ink max-w-none">
          <p className="text-ink-600 text-lg leading-relaxed mb-6">
            These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the Composable platform and services provided by Composable Technologies Inc. By accessing or using our services, you agree to be bound by these Terms.
          </p>

          {[
            {
              title: '1. Definitions',
              body: '"Customer" means the employer entity that has entered into a subscription agreement with Composable. "Employee Users" means the employees of Customer who access the platform to make compensation elections. "Platform" means the Composable compensation infrastructure software and associated services. "Content" means data, text, and information submitted to or generated by the Platform.',
            },
            {
              title: '2. Access and Use',
              body: "Subject to these Terms, Composable grants Customer a non-exclusive, non-transferable license to access and use the Platform during the subscription term. Customer is responsible for all activity under its account. Customer agrees not to: reverse engineer or attempt to extract source code; resell or sublicense the Platform; use the Platform to store or transmit malicious code; or use the Platform in violation of applicable law.",
            },
            {
              title: '3. Data and Privacy',
              body: "Customer retains ownership of all data submitted to the Platform. Composable processes this data as a service provider under Customer's instructions. Composable's collection and use of data is governed by our Privacy Policy. Customer is responsible for obtaining necessary consents from Employee Users before submitting their data to the Platform.",
            },
            {
              title: '4. Compliance',
              body: "Composable provides tools designed to assist with CRA and IRS compliance, but does not provide tax, legal, or financial advice. The tax estimates provided by our calculator are for informational purposes. Customer remains responsible for the accuracy of all compensation decisions and the compliance of its compensation programs under applicable law.",
            },
            {
              title: '5. Service Levels',
              body: "Composable will use commercially reasonable efforts to maintain Platform availability. Scheduled maintenance will be communicated at least 48 hours in advance where possible. Enterprise customers with SLA agreements are governed by the terms of their specific agreement.",
            },
            {
              title: '6. Intellectual Property',
              body: "Composable owns all intellectual property rights in the Platform, including software, design, and documentation. Customer grants Composable a limited license to use Customer's trademarks and branding solely to provide the branded Total Rewards Statements and related features.",
            },
            {
              title: '7. Termination',
              body: "Either party may terminate upon written notice if the other party materially breaches these Terms and fails to cure the breach within 30 days. Upon termination, Composable will provide Customer with a data export within 30 days and delete Customer data within 90 days thereafter.",
            },
            {
              title: '8. Governing Law',
              body: 'These Terms are governed by the laws of the Province of Ontario and the federal laws of Canada applicable therein. Disputes shall be resolved through binding arbitration in Toronto, Ontario, except that either party may seek injunctive relief in any court of competent jurisdiction.',
            },
          ].map((section) => (
            <div key={section.title} className="mb-8">
              <h2 className="font-display text-xl font-bold text-ink-950 mb-3">{section.title}</h2>
              <p className="text-ink-600 leading-relaxed">{section.body}</p>
            </div>
          ))}

          <div className="mt-10 p-5 bg-ink-50 border border-ink-200 rounded-2xl">
            <p className="text-sm text-ink-600">
              Questions? Contact us at <a href="mailto:legal@getcomposable.com" className="text-brand-600 hover:underline">legal@getcomposable.com</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  )
}
